databases:
  - name: search_analytics_tracker
    databaseName: search_analytics_tracker
    user: search_analytics_tracker

services:
  - type: web
    name: search_analytics_tracker
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: search_analytics_tracker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
      value: 2



        